# Generated by Django 3.0.2 on 2020-02-13 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=200, verbose_name='Альбом')),
                ('text', models.TextField(default=True, verbose_name='Описание')),
                ('image', models.URLField(blank=True, default=True, null=True, verbose_name='Изображение')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=True, max_length=200, verbose_name='Название')),
                ('image', models.URLField(default=True, verbose_name='Изображение')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Rubrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=200, verbose_name='Название')),
                ('text', models.TextField(default=True, verbose_name='Текст')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текста',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=200, verbose_name='Название')),
                ('video', embed_video.fields.EmbedVideoField(default=True, verbose_name='Видео')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('rubric', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='main.Rubrics', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(default=True, verbose_name='Описание')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, default=True, verbose_name='Видео')),
                ('image', models.URLField(blank=True, default=True, null=True, verbose_name='Изображение')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=True, max_length=200, verbose_name='Название')),
                ('music', models.URLField(default=True, verbose_name='Музыка')),
                ('image', models.URLField(blank=True, default=True, null=True, verbose_name='Изображение')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('album', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.Albums', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Музыка',
                'verbose_name_plural': 'Музыки',
            },
        ),
    ]
