# Generated by Django 3.0.2 on 2020-02-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rubric_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Альбом')),
                ('text', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='media', verbose_name='Изображение')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['-published'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('music', models.FileField(upload_to='audio', verbose_name='Музыка')),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Album', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Музыка',
                'verbose_name_plural': 'Музыки',
            },
        ),
    ]
