# Generated by Django 3.0.2 on 2020-02-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200214_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.URLField(blank=True, null=True, verbose_name='Источник'),
        ),
    ]
