# Generated by Django 3.0.2 on 2020-02-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200211_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rubric',
            new_name='Rubrics',
        ),
    ]
