# Generated by Django 3.0.2 on 2020-02-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200211_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Albums',
        ),
        migrations.RenameModel(
            old_name='Music',
            new_name='Musics',
        ),
    ]
