# Generated by Django 3.0.2 on 2020-02-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200211_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текста',
                'ordering': ['-published'],
            },
        ),
    ]
