# Generated by Django 3.0.3 on 2020-02-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200220_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
