# Generated by Django 3.0.3 on 2020-02-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200220_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Images', verbose_name='Фотки'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.News', verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='texts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Texts', verbose_name='Текста'),
        ),
    ]
