# Generated by Django 3.0.3 on 2020-02-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200220_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
    ]
